config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
get 'users/feed', to: 'users#feed', as: 'feed'
get 'posts/opinions', to: 'comments#opinions', as: 'opinions'
get 'posts/portfolio', to: 'posts#portfolio', as: 'portfolio'
get 'users/top', to: 'users#top', as: 'top_users'
get 'posts/top', to: 'posts#top', as: 'top'
get 'posts/topday', to: 'posts#topday', as: 'top_day'
get 'posts/topweek', to: 'posts#topweek', as: 'top_week'
get 'posts/topmonth', to: 'posts#topmonth', as: 'top_month'
get 'posts/topyear', to: 'posts#topyear', as: 'top_year'
get 'posts/loved', to: 'posts#loved', as: 'loved'
get 'posts/lovedday', to: 'posts#lovedday', as: 'loved_day'
get 'posts/lovedweek', to: 'posts#lovedweek', as: 'loved_week'
get 'posts/lovedmonth', to: 'posts#lovedmonth', as: 'loved_month'
get 'posts/lovedyear', to: 'posts#lovedyear', as: 'loved_year'
get 'posts/hated', to: 'posts#hated', as: 'hated'
get 'posts/hatedday', to: 'posts#hatedday', as: 'hated_day'
get 'posts/hatedweek', to: 'posts#hatedweek', as: 'hated_week'
get 'posts/hatedmonth', to: 'posts#hatedmonth', as: 'hated_month'
get 'posts/hatedyear', to: 'posts#hatedyear', as: 'hated_year'
get 'user/:id', to: 'users#show', as: 'user_profile'
	
  resources :posts do
    resources :comments
	member do
		get 'like'
		get 'dislike'
	end
  end
	resources :comments do
		  member do
		    get 'like'
		    get 'dislike'
	  end
	end
	
    
	resources :users do
    member do
      get :following, :followers
    end
  end

resources :relationships,       only: [:create, :destroy]
  

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	# has_ancestry
	default_scope { order('cached_weighted_total DESC') }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end
	
	def opinions
	 @comments = current_user.comments.paginate(page: params[:page], :per_page => 33).order('created_at DESC') 
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
	@post = Post.find(params[:post_id])
  @comment = Comment.new
	# @comment.parent_id = params[:parent_id]
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
	@post = Post.find(params[:post_id])
  @comment = @post.comments.build(comment_params)
	@comment.user_id = current_user.id
	@comment.post_id = @post.id
    respond_to do |format|
      if @comment.save
		format.js
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
    if @comment.destroy
    respond_to do |format|
	  format.js
      #format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

def like
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:comment_id])
  @comment.liked_by current_user
  respond_to do |format|
    format.html { redirect_to @post }
	 format.js
  end
 end

  def dislike
	  @post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:comment_id])
  @comment.disliked_by current_user
  respond_to do |format|
    format.html { redirect_to @post }
    format.js
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body, :ancestry)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
  comments.map do |comment, sub_comments|
    render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
  end.join.html_safe
end
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>

<div id='comment-<%= comment.id %>'>

	<%= comment.body %>

		<br><br>
	
<% if comment.id.present? %>
<%= hidden_field_tag y = comment.cached_comments_up %>
<span>
<%=y%>
</span>


<% if (current_user) && (comment.user_id != current_user.id) && (current_user.voted_up_on? comment) %>
	<%= link_to '√', like_comment_path(id: comment.id, comment_id: comment.id, post_id: @post), remote: true, id: "commentlike", class: 'commentliked'%>
	|
<%= link_to 'X', dislike_comment_path(id: comment.id, comment_id: comment.id, post_id:  @post), remote: true, id: "commentdislike", class: 'commentdisliked'%>



<%elsif (current_user) && (comment.user_id != current_user.id) && (current_user.voted_down_on? comment) %>
<%= link_to '√', like_comment_path(id: comment.id, comment_id: comment.id, post_id:  @post), remote: true, id: "commentlike", class: 'commentdisliked'%>
|
<%= link_to 'X', dislike_comment_path(id: comment.id, comment_id: comment.id, post_id:  @post), remote: true, id: "commentdislike", class: 'commentliked'%>

<%elsif (current_user) && (comment.user_id == current_user.id)%>
 <span id='like'>√</span> | <span id='dislike'>X</span>

<%else%>
<%= link_to '√', like_comment_path(id: comment.id, comment_id: comment.id,post_id:  @post), remote: true, id: "commentlike", class: 'commentlike'%>
 | 
<%= link_to 'X', dislike_comment_path(id: comment.id, comment_id: comment.id,post_id:  @post), remote: true, id: "commentdislike", class: 'commentdislike' %>
<%end%>
	


<%= hidden_field_tag z = comment.cached_comments_down %>
<span>
<%=z%>
</span>
<%end%>

	
<br>


	
  
    <small><%= comment.created_at.try(:strftime,"%b %d %Y at %I:%M%p")
%></small>

	<div>
	<% if comment.user.present? %>
	<%= link_to user_profile_path(comment.user.id), {style: 'text-decoration:none'}  do %>
	<%= comment.user.username %>
	
	<br>
	<%= image_tag(comment.user.avatar(:tiny), class: 'show-avatar') %>
	<br>
	<%end%>
	<%end%>

	<% if current_user %>
<%#= link_to 'Reply', new_post_comment_path(:parent_id=>comment, :post_id => @post) %>
<% if comment.user_id == current_user.id %>

<%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
		
		
<%end%>
		<%end%>
</div>

		
		</div>
	<br>
<br>


<%end%>

app/views/comments/_commentform.html.erb
<%= form_for [@post, @comment], remote: true do |form| %>
  <%= form.hidden_field :parent_id %>

  <div class="field">
    <%= form.label :body, 'Opinion' %>
    <%= form.text_area :body, id: :comment_body, rows: 4, cols: 60, placeholder: 'Share your opinion...' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment || @post.comments.build], remote: true do |form| %>
 

  <div class="field">
    <%= form.label :body, 'Opinion' %>
    <%= form.text_area :body, id: :comment_body, rows: 4, cols: 60, placeholder: 'Share your opinion...' %>
  </div>

  <div class="actions">
    <%= form.submit 'Share Opinion' %>
  </div>
<% end %>

app/views/comments/_vote.html.erb
<% @post.comments.find(params[:comment_id]) do |comment| %>

<% if comment.id.present? %>
<%= hidden_field_tag y = comment.get_likes.size %>
<span id='commentlikes'>
<%=y%>
</span>

<% if current_user.voted_up_on? comment %>
	<%= link_to '√', like_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentlike_#{@comment.id}', class: 'commentlike commentliked'%>
	|
<%= link_to 'X', dislike_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentdislike_#{@comment.id}', class: 'commentdislike commentdisliked'%>



<%elsif current_user.voted_down_on? comment %>
<%= link_to '√', like_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentlike_#{@comment.id}', class: 'commentlike commentdisliked'%>
|
<%= link_to 'X', dislike_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentdislike_#{@comment.id}', class: 'commentdislike commentliked'%>



<%else%>
<%= link_to '√', like_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentlike_#{@comment.id}', class: 'commentlike'%>
 | 
<%= link_to 'X', dislike_post_comment_path(@post, comment_id: comment.id), remote: true, id: 'commentdislike_#{@comment.id}', class: 'commentdislike' %>
<%end%>

<%= hidden_field_tag z = comment.get_dislikes.size %>
<span id='commentdislikes'>
<%=z%>
</span>
<%end%>

<%end%>

app/views/comments/create.js.erb
$('#comments').html("<%= j render 'comments/comment' %>");
$('#comment_body').val("");
var count = $("#count").text();
var newCount = +count + 1;
$('#count').text(newCount);

app/views/comments/destroy.js.erb
var comment = $('div#comment-<%= @comment.id %>');
comment.fadeOut(function () {
  $(this).remove();
});
var count = $("#count").text();
var newCount = count - 1;
$('#count').text(newCount);

app/views/comments/dislike.js.erb
$('#comments').html("<%= j render'comments/comment' %>");
$('#votes').html("<%= j render'posts/vote' %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--> <%= link_to 'New Comment', new_comment_path %> -->

app/views/comments/like.js.erb
$('#comments').html("<%= j render 'comments/comment' %>");
$('#votes').html("<%= j render 'posts/vote' %>");

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render @comment.parent if @comment.parent %>

<%= hidden_field_tag x = @comment.parent.children.count %>
<div id="link-container"><h3 class="comments-link"><span id='count'><%= x %></span> Opinion<% if x  ===0 || x > 1%>s<%end%></h3></div>

<%= render 'commentform', comment: @comment %>




<section id="comments-section">
  <div id="comments">
	  
    <%= render(partial: 'comments/comment', collection: @comments) %>
  </div>
    <%if x > 0 %>
    <div id="link-container"><h3 class="comments-link">Hide Opinions</h3></div>
    <% end %>
</section>

<%= link_to 'Back', @post %>

app/views/comments/opinions.html.erb
<p id="notice"><%= notice %></p>

<table>
  
<% current_user.comments.each do |comment| %>
    
    
  <tbody>
      <tr>
          <td><%= link_to post_path(comment.post_id), {style: 'text-decoration:none'}  do %>
			  
              <div class='clickable'>
				  
				  <div>
					  <span><%= comment.cached_comments_up %> <span id='like'>√</span> |</span>
					  <span id='dislike'>X</span><span> <%= comment.cached_comments_down%></span>
				  </div>
				  
              		<%=comment.body %>
				  <div><small><%= comment.created_at.try(:strftime,"%b %d %Y at %H:%M")
%></small></div>
				  <%end%>
				  
				  
				  <!--<%#= link_to 'Destroy', post_comment_path(comment.post_id, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>-->
            
            
			  </div>
          </td>
      </tr>
      <% end %>
    
  </tbody>
    
</table>



<!-- #<%= link_to 'New Post', new_post_path %> -->

<h1 id="infinite-scrolling">
  <%= will_paginate %>
	<br>
	<br>
</h1>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>