config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
get 'users/feed', to: 'users#feed', as: 'feed'
get 'posts/opinions', to: 'comments#opinions', as: 'opinions'
get 'posts/portfolio', to: 'posts#portfolio', as: 'portfolio'
get 'users/top', to: 'users#top', as: 'top_users'
get 'posts/top', to: 'posts#top', as: 'top'
get 'posts/topday', to: 'posts#topday', as: 'top_day'
get 'posts/topweek', to: 'posts#topweek', as: 'top_week'
get 'posts/topmonth', to: 'posts#topmonth', as: 'top_month'
get 'posts/topyear', to: 'posts#topyear', as: 'top_year'
get 'posts/loved', to: 'posts#loved', as: 'loved'
get 'posts/lovedday', to: 'posts#lovedday', as: 'loved_day'
get 'posts/lovedweek', to: 'posts#lovedweek', as: 'loved_week'
get 'posts/lovedmonth', to: 'posts#lovedmonth', as: 'loved_month'
get 'posts/lovedyear', to: 'posts#lovedyear', as: 'loved_year'
get 'posts/hated', to: 'posts#hated', as: 'hated'
get 'posts/hatedday', to: 'posts#hatedday', as: 'hated_day'
get 'posts/hatedweek', to: 'posts#hatedweek', as: 'hated_week'
get 'posts/hatedmonth', to: 'posts#hatedmonth', as: 'hated_month'
get 'posts/hatedyear', to: 'posts#hatedyear', as: 'hated_year'
get 'user/:id', to: 'users#show', as: 'user_profile'
	
  resources :posts do
    resources :comments
	member do
		get 'like'
		get 'dislike'
	end
  end
	resources :comments do
		  member do
		    get 'like'
		    get 'dislike'
	  end
	end
	
    
	resources :users do
    member do
      get :following, :followers
    end
  end

resources :relationships,       only: [:create, :destroy]
  

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#", tiny: "30x30#" }, default_url: "person_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	
	acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts
	has_many :comments
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	
	def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
	
  def sum_score
	  @score = 0
	posts.each do |post|
	  @postscore = post.weighted_score
	  @score += @postscore
	end
	comments.each do |comment|
	  @commentscore = comment.cached_weighted_score
	  @score += @commentscore * 10
	end
	  @followers = followers.count * 10
	  @score += @followers
	  return @score
  end
	
	def user_rank
		ary = [] 
		@users = User.all
		@users.each do |user|
			ary.push(user.sum_score)
		end
		newAry = ary.sort { |a,b| b.to_i <=> a.to_i }
		@user = User.find(id)
		return newAry.index(@user.sum_score) + 1
	end
	
	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
	@users = User.all.paginate(:page => params[:page], :per_page => 33).order('id ASC')
	end
	
	def top
		
	@users = User.all.paginate(:page => params[:page], :per_page => 33).sort{|a, b| b.sum_score <=> a.sum_score}
	end
	
	def show
    @user = User.find(params[:id])
	@posts = @user.posts.paginate(:page => params[:page], :per_page => 33).order('created_at DESC')
	render 'users/show'
  end
	
	def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = #{current_user.id}"
    @posts = Post.where("#{:user_id} IN (#{following_ids})")
                     
  end

	
	
	def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'users/show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'users/show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed.html.erb
<p id="notice"><%= notice %></p>
<% if @posts.count === 0 %>
<br><br>
<h2>Find Authors to subscribe to!</h2>
<%end%>
<table>
  <!--<thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
-->
<% @posts.each do |post| %>
    
    
  <tbody>
    
      <tr>
          <td><%= link_to post, {style: 'text-decoration:none'}  do %>
              <div class='clickable'>
              <p id='post-title'><%= truncate(strip_tags(post.title), length: 100) %></p>
			  <!--<p id='post-user'>By <br>
				  <%# post.user.username %></p>-->
            <% if post.image.exists? %>
        <%= image_tag(post.image(:thumb)) %>
        <% elsif post.video.exists? %>

        <%= image_tag(post.video(:thumb)) %>
            <% end %>
				  
            <p id='post-body'><%= truncate(strip_tags(post.body), length: 200) %></p>
            
    </div>
              <%end%>
          </td>
          
        <!--<%= link_to 'Show', post %></td>-->
        <!--<td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
      <% end %>
    
  </tbody>
    
</table>



<!-- #<%= link_to 'New Post', new_post_path %> -->

<h1 id="infinite-scrolling">
  
	<br>
	<br>
</h1>

app/views/users/index.html.erb
<table>
<% @users.each do |user| %>
<tbody>
	<tr>
		<td><div class='user-cell'>
<%= link_to user_profile_path(user), {style: 'text-decoration:none'}  do %>

<div><%= user.username %></div>
<div><%= image_tag(user.avatar(:thumb), class: 'show-avatar') %></div>
			</div></td>
<% end %>
		<tr>
<%end%>
	  
	</tbody>
</table>

app/views/users/show.html.erb
<% if current_user.username == @user.username %> <div><%= link_to 'Edit Resume', edit_user_registration_path%></div> <%end%>
<div>
<%= @user.username %>
	</div>
<div>
<%= image_tag(@user.avatar, class: 'show-avatar') %>
	</div>
<br>
<section class="stats">
        <%= render 'devise/shared/stats' %>
      </section>
<div><%= render 'devise/shared/follow_form' %></div>
<br>
<%= link_to 'Back', :back %>

app/views/users/show_follow.html.erb
<div>
  
    <section>
		<% if (current_user) && (current_user.username == @user.username) %> <div><%= link_to 'Edit Resume', edit_user_registration_path%></div> <%end%>
<br>
		<h1><%= @user.username %></h1>
      <%= link_to image_tag(@user.avatar(:medium), class: 'show-avatar'), @user %>
      
      <div><b>posts:</b> <%= @user.posts.count %></div>
		<div><b>comments:</b> <%= @user.comments.count %></div>
    </section>
    <section class="stats">
      <%= render 'devise/shared/stats' %>
	  </section>
		
      <% if @users.any? %>
        <div class="user_avatars">
			<table
          <% @users.each do |user| %>
			<tbody>
	<tr>
		<td>
			<div><%= user.username %></div>
            <div><%= link_to image_tag(user.avatar(:thumb), class: 'show-avatar'), user_profile_path(user) %>
				
			</div>
			</td>
          <% end %>
			</tr>
        </div>
      <% end %>
		</tbody>
	  </table>
   
 
  <div class="col-md-8">
    
    <% if @users.any? %>
      <ul class="users follow">
        
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>

app/views/users/top.html.erb
<table>
  <% @users.first(33).each do |user| %>
    <% @score = 0 %>
    <tbody>
      <tr>
        <td class="user-rank" id="<%= @score %>">
          <%= link_to user_profile_path(user), {class: 'clickable'}  do %>
            <div class="rank">_</div>
            <div class="score">
              Rating: <%=user.sum_score%>
            </div>
            <div>
              <%= user.username %>
            </div>
            <div>
              <%= image_tag(user.avatar(:thumb), class: 'show-avatar') %>
            </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>
<script>
  
  $(document).ready(function() {
  	$('.rank').each(function(i) {
  		$(this).text('#'+(1+i++));
  	});
  });


</script>