config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
get 'users/feed', to: 'users#feed', as: 'feed'
get 'posts/opinions', to: 'comments#opinions', as: 'opinions'
get 'posts/portfolio', to: 'posts#portfolio', as: 'portfolio'
get 'users/top', to: 'users#top', as: 'top_users'
get 'posts/top', to: 'posts#top', as: 'top'
get 'posts/topday', to: 'posts#topday', as: 'top_day'
get 'posts/topweek', to: 'posts#topweek', as: 'top_week'
get 'posts/topmonth', to: 'posts#topmonth', as: 'top_month'
get 'posts/topyear', to: 'posts#topyear', as: 'top_year'
get 'posts/loved', to: 'posts#loved', as: 'loved'
get 'posts/lovedday', to: 'posts#lovedday', as: 'loved_day'
get 'posts/lovedweek', to: 'posts#lovedweek', as: 'loved_week'
get 'posts/lovedmonth', to: 'posts#lovedmonth', as: 'loved_month'
get 'posts/lovedyear', to: 'posts#lovedyear', as: 'loved_year'
get 'posts/hated', to: 'posts#hated', as: 'hated'
get 'posts/hatedday', to: 'posts#hatedday', as: 'hated_day'
get 'posts/hatedweek', to: 'posts#hatedweek', as: 'hated_week'
get 'posts/hatedmonth', to: 'posts#hatedmonth', as: 'hated_month'
get 'posts/hatedyear', to: 'posts#hatedyear', as: 'hated_year'
get 'user/:id', to: 'users#show', as: 'user_profile'
	
  resources :posts do
    resources :comments
	member do
		get 'like'
		get 'dislike'
	end
  end
	resources :comments do
		  member do
		    get 'like'
		    get 'dislike'
	  end
	end
	
    
	resources :users do
    member do
      get :following, :followers
    end
  end

resources :relationships,       only: [:create, :destroy]
  

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/views/layouts/_bottomnav.html.erb
<nav class="bnavbar">
  <div class="bdropdown">
    <% if current_user %>
      <%= link_to image_tag(current_user.avatar(:tiny), class: 'show-avatar bnav-av'), user_profile_path(current_user) %>
      <button class="bdropbtn">
        <%= link_to 'Subs', feed_path, class: 'blink clickable' %>
      </button>
      <button class="bdropbtn">
        <%= link_to 'Publish', new_post_path, class: 'blink clickable' %>
      </button>
      <button class="bdropbtn">
        <%= link_to 'Opinions', opinions_path, class: 'blink clickable' %>
      </button>
      <button class="bdropbtn">
        <%= link_to 'Logout', destroy_user_session_path, class: 'blink clickable', method: :delete %>
      </button>
    <% else %>
      <button class="bdropbtn">
        <%= link_to 'Sign In', new_user_session_path, class: 'blink clickable' %>
      </button>
      <button class="bdropbtn">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'blink clickable' %>
      </button>
    <% end %>
  </div>
</nav>

app/views/layouts/_topnav.html.erb
<!--<div class="top">
<div class="nav">
      <ul>
          
          <li><a><%= link_to 'New', posts_path, class: :link %></a>
          <ul>
            <li><a href="#">Today</a></li>
            <li><a href="#">Last Week</a></li>
            <li><a href="#">Last Month</a></li>
            <li><a href="#">Last year</a></li>
            <li><a href="#">All Time</a></li>
          </ul>
        </li>
        
        <li><a><%= link_to 'Top', top_path, class: :link %></a>
          <ul>
            <li><a href="#">Today</a></li>
            <li><a href="#">Last Week</a></li>
            <li><a href="#">Last Month</a></li>
            <li><a href="#">Last year</a></li>
            <li><a href="#">All Time</a></li>
          </ul>
        </li>
          
          <li><a><%= link_to 'Loved', loved_path, class: :link %></a>
          <ul>
            <li><a href="#">Today</a></li>
            <li><a href="#">Last Week</a></li>
            <li><a href="#">Last Month</a></li>
            <li><a href="#">Last year</a></li>
            <li><a href="#">All Time</a></li>
          </ul>
        </li>
          
          <li><a><%= link_to 'Hated', hated_path, class: :link %></a>
          <ul>
            <li><a href="#">Today</a></li>
            <li><a href="#">Last Week</a></li>
            <li><a href="#">Last Month</a></li>
            <li><a href="#">Last year</a></li>
            <li><a href="#">All Time</a></li>
          </ul>
        </li>
          
          <li><a><%= link_to 'Ranked', top_users_path, class: :link %></a>
          <ul>
            <li><a href="#">Top</a></li>
            <li><a href="#">Loved</a></li>
            <li><a href="#">Hated</a></li>
          </ul>
        </li>
        
      </ul>
    </div>
</div>

<script>
     $(function() {
        $('#nav li a ').click(function() {
           $(this).addClass("active");
        });
     });
  </script>
-->
  <div class="topnav" id="myTopnav">
      <%=link_to 'News', posts_path, class:'nav-link'%>
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn">Top</button>
    <div id="myDropdown" class="dropdown-content">
        <%= link_to 'Day', top_day_path, class:'navlink' %>
        <%= link_to 'Week', top_week_path, class:'navlink' %>
        <%= link_to 'Month', top_month_path, class:'navlink' %>
        <%= link_to 'Year', top_year_path, class:'navlink' %>
        <%= link_to 'All Time', top_path, class:'navlink' %>
      </div>
  </div>
  <div class="dropdown">
    <button onclick="myFunction2()" class="dropbtn">Loved</button>
    <div id="myDropdown2" class="dropdown-content">
      <%= link_to 'Day', loved_day_path, class:'navlink' %>
      <%= link_to 'Week', loved_week_path, class:'navlink' %>
      <%= link_to 'Month', loved_month_path, class:'navlink' %>
      <%= link_to 'Year', loved_year_path, class:'navlink' %>
      <%= link_to 'All Time', loved_path, class:'navlink' %>
    </div>
  </div>
  <div class="dropdown">
  <button onclick="myFunction3()" class="dropbtn">Hated</button>
    <div id="myDropdown3" class="dropdown-content">
      <%= link_to 'Day', hated_day_path, class:'navlink' %>
      <%= link_to 'Week', hated_week_path, class:'navlink' %>
      <%= link_to 'Month', hated_month_path, class:'navlink' %>
      <%= link_to 'Year', hated_year_path, class:'navlink' %>
      <%= link_to 'All Time', hated_path, class:'navlink' %>
    </div>
  </div>
  <%= link_to 'Ranked', top_users_path, class:'nav-link' %>
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>

<script>
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<script>
function myFunction2() {
    document.getElementById("myDropdown2").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<script>
function myFunction3() {
    document.getElementById("myDropdown3").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Poll</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render "layouts/topnav" %>
	  <br>
	  <br>
	  <br>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>
	  <br>
	  
<%= render "layouts/bottomnav" %>

  </body>
</html>